spring:
  cloud:
    function:
      scan:
        packages: com.example.springcloudfunctiondemo.function
    web:
      export:
        enabled: true
        debug: false
  main:
    web-application-type: none

